version: '3.8'
services:
  firebase-tools:
    build:
      context: ./firebase-tools
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4600:4600"
      - "5001:5001"
      - "8080:8080"
      - "8085:8085"
      - "9000:9000"
      - "9099:9099"
      - "9229:9229"
  pubsub-provisioner:
    image: jonnyorman/pubsub-provisioner:latest
    depends_on:
      - firebase-tools
    environment:
      PUBSUB_EMULATOR_HOST: firebase-tools:8085
      PUBSUB_CONFIG:
        '{
          "projectId": "pubsub-provisioner-example",
          "topics": [
            {
              "topicId": "my-topic",
              "subscriptions": [
                {
                  "type": "push",
                  "subscriptionId": "my-topic-subscription",
                  "ackDeadlineSeconds": 10,
                  "pushEndpoint": "http://my-push-endpoint:1234"
                }
              ]
            }
          ]
        }'