version: '3.8'
services:
  firebase-tools:
    build:
      context: ./firebase-tools
  pubsub-provisioner:
    image: jonnyorman/pubsub-provisioner:latest
    depends_on:
      - firebase-tools
    environment:
      PUBSUB_EMULATOR_HOST: firebase-tools:8085
      PUBSUB_CONFIG:
        '{
          "projectId": "pubsub-provisioner-example",
          "topics": [
            {
              "topicId": "my-topic",
              "subscriptions": [
                {
                  "type": "push",
                  "subscriptionId": "my-topic-subscription",
                  "ackDeadlineSeconds": 10,
                  "pushEndpoint": "http://my-push-endpoint:1234"
                }
              ]
            }
          ]
        }'